### ISSUE TITLE
The current build fails in relation to NL2015, can somebody fix it?

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1374]
![screen shot 2017-10-11 at 16 45 56](https://user-images.githubusercontent.com/2676542/31448020-ada4186e-aea3-11e7-8aa5-485d626a359c.png)

**In short:**
Semaphore is turned off in ETSource for reasons. In the mean time, somebody should fix these specs:

**Rspec results**

```
Failures:

  1) Load profiles for NL2015 buildings_chp.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 0.9999881639999776 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

  2) Load profiles for NL2015 electric_vehicle_profile_3.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 1.0001072952000007 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

  3) Load profiles for NL2015 electric_vehicle_profile_2.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 0.9998792640000173 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

  4) Load profiles for NL2015 electric_vehicle_profile_1.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 1.0001038680000138 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

  5) Load profiles for NL2015 dhw_normalized.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 1.0000105199999978 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

  6) Load profiles for NL2015 agriculture_chp.csv should have values summing to 1/3600
     Failure/Error: expect(in_joules).to be_within(1e-7).of(1.0)
       expected 1.0004025599999815 to be within 1.0e-07 of 1.0
     # ./spec/load_profiles_spec.rb:38:in `block (5 levels) in <top (required)>'

Finished in 23.2 seconds
11378 examples, 7 failures, 11 pending

Failed examples:

rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 electric_vehicle_profile_2.csv should have values summing to 1/3600
rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 dhw_normalized.csv should have values summing to 1/3600
rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 electric_vehicle_profile_3.csv should have values summing to 1/3600
rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 buildings_chp.csv should have values summing to 1/3600
rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 agriculture_chp.csv should have values summing to 1/3600
rspec ./spec/load_profiles_spec.rb:31 # Load profiles for NL2015 electric_vehicle_profile_1.csv should have values summing to 1/3600

Randomized with seed 1205
```

@antw what is the status of the Semaphore CI problem? Would you like me to look at it? 

*Small rant, sort of*:
Also, just because Semaphore isn't checking if your build is not passing, you should still check if it's working ..... I do get that it's a bit counterintuitive for a non-developer to be running `rspec` everytime, but I don't know what else to suggest. 😅

**Comment by ChaelKruip** [comment]
> No such file or directory @ rb_sysopen - /Users/gerard/Projects/etsource/datasets/nl2015/energy_balance.csv

Looks like you need to run a `rake decrypt` first @grdw 

The other failures are already on the list of @DorinevanderVlies and are not very critical

**Comment by DorinevanderVlies** [comment]
I'll fix this today!
