### ISSUE TITLE
Removing the full load hours from transport_truck_using_electricity.converter breaks some gqueries

### ISSUE THREAD

**Issue by grdw** [quintel/etsource#1475]
https://github.com/quintel/etsource/commit/c1addacfb2a95cc85ce86af981d15151d3a767dc 

I hate to say it - but this is the actual culprit that causes ETModel to fail.

The following gql's are affected:

0 | dashboard_total_costs/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/eten…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
-- | --
1 | policy_goal_total_energy_costs_reached/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/ger…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
2 | policy_goal_total_energy_costs_value/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerar…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
3 | peak_load_check_lv/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/etengin…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
4 | peak_load_check_mv_lv/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/eten…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
5 | peak_load_check_mv/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/etengin…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
6 | peak_load_check_hv_mv/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/eten…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
7 | peak_load_check_total/future - undefined method *' for nil:NilClass \| /Users/gerard/Projects/etengine/app/models/gql/runtime/functions/core.rb:205:ininstance_eval'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:15:in block in number_of_units'/Users/gerard/Projects/etengine/app/models/qernel/dataset_attributes.rb:204:infetch'/Users/gerard/Projects/etengine/app/models/qernel/converter_api/helper_calculations.rb:12:in number_of_units'/Users/gerard/Projects/eten…ncall'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in call'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:inservice'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:138:in service'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/httpserver.rb:94:inrun'/Users/gerard/.rbenv/versions/2.1.9/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by marliekeverweij** [comment]
This issue is already fixed right? Because `transport_truck_using_electricity` has full load hours again?

**Comment by ChaelKruip** [comment]
> Because transport_truck_using_electricity has full load hours again?

Did you check this? You could look in the Sandbox and run a query for the trucks:

```
V(transport_truck_using_electricity, full_load_hours)
```
